# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/currency_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# Liquibase
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.sql
spring.liquibase.enabled=true