version: '3'

services:
  postgres:
    image: postgres:13
    container_name: currency_postgres
    environment:
      POSTGRES_DB: currency_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: bank-app-t-bank:0.0.1-SNAPSHOT
    container_name: currency_app
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      APP_ENV: production
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/currency_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGE-LOG: "classpath:/db/changelog/db.changelog-master.xml"
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data: